name: Ruff format and check
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python requirements
        run: pip install -r requirements/lint_format.txt
      - uses: astral-sh/ruff-action@v3
        with:
          src: GeoLinesQC
          args: format
      - uses: astral-sh/ruff-action@v3
        with:
          src: GeoLinesQC
          args: check
